# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3e93eaa120ff45bd12401d8ae08d48f572fcb26914086380fe6c9615045c0dcab26aa4f9301389444aad608112489721fb8c3cb25cc6185d2f18eda7784f042

test:
  secret_key_base: 4ea7002f0380b9002b7954d5d08259f34dc475191eee96e2857094a48c47197683cabc7bf6e176ea1df43d0685b1925d46cd3e625aecf6b8f66d862038ee35e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
